/** @type {import('semantic-release').GlobalConfig} */
export default {
  extends: 'semantic-release-monorepo',
  branches: ['master'],
  tagFormat: 'cli-v${version}',
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    [
      '@semantic-release/changelog',
      {
        changelogFile: 'CHANGELOG.md',
        changelogTitle: '# Changelog\n\nReleases of `@cookiemonsterdev/kafka-cli`. Generated by semantic-release.',
      },
    ],
    [
      '@semantic-release/exec',
      {
        prepareCmd: 'pnpm exec prettier --write CHANGELOG.md',
        publishCmd: 'npm publish --access public --registry https://registry.npmjs.org/',
      },
    ],
    [
      '@semantic-release/npm',
      {
        npmPublish: false,
      },
    ],
    [
      '@semantic-release/git',
      {
        assets: ['package.json', 'CHANGELOG.md'],
        message: 'chore(cli): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}',
      },
    ],
    [
      '@semantic-release/github',
      {
        releasedLabels: false,
        successComment: false,
        failTitle: false,
        failComment: false,
      },
    ],
  ],
};
